- name: Bare include (free-form)
  include_vars: "{{ project_dir }}/inventory/rhel8_host_vars"
  ignore_errors: no 

- name: Copying over idm_dns this will be used to for the idm dns server variables
  template:
    src: templates/idm_dns.yml.j2
    dest:  /{{ vm_inventory_dir }}/idm_dns.yml
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: 0666