- name: Copying over rhel_vm this will be used to configure your rhel vm variables
  template:
    src: templates/rhel_vm.yml.j2
    dest:  "/{{ vm_inventory_dir }}/{{ rhel_name }}.yml"
    owner: admin
    group: admin
    mode: 0666